name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
    uses: ./.github/workflows/_release-reusable.yml
    with:
      tag: ${{ github.ref_name }}
